.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Add github Issue template and PR template.

chore: add issue template

---

README.md
docs/user-guide/getting-started_zh.md

Add Readme

---

Release_Note.md
docs/user-guide/getting-started.md
docs/user-guide/getting-started_zh.md

modify sealer docs url

---

build/Kubefile
build/charts/l-zero/templates/l0_utils.configmap.yaml
build/plugins/trident_preflight_shell_plugin.yaml

modify Kubefile

---

docs/FAQ.md
docs/FAQ_zh.md

Update FAQ.md to clarify version strategy

---

build/Clusterfile
build/Kubefile
build/plugins/disk_init_on_master_shell_plugin.yaml
build/plugins/disk_init_rollback_on_master_shell_plugin.yaml
build/plugins/disk_init_rollback_shell_plugin.yaml
build/plugins/disk_init_shell_plugin.yaml
build/plugins/health_check_shell_plugin.yaml
build/plugins/install_addons_shell_plugin.yaml
build/plugins/preflight_shell_plugin.yaml
build/scripts/disk_init_rollback.sh
build/scripts/install_addons.sh

修改了plugin Clusterfile Kubefile

modify ack

---

build/plugins/disk_init_rollback_shell_plugin.yaml
build/plugins/disk_init_shell_plugin.yaml

modify name

---

build/charts/hybridnet/values.yaml

modify defult image

---

build/charts/hybridnet/templates/daemonsets.yaml
build/charts/hybridnet/values.yaml
build/charts/open-local/values.yaml
build/imageList

fix hybrident bug

---

build/kubeadm.yml

modify kubeadm.yml 1.20.4-aliyun.1 ---> v1.20.4-aliyun.1

---

build/imageList

modify imagelist

---

build/build.sh
build/charts/hybridnet/Chart.yaml
build/charts/hybridnet/README.md
build/charts/hybridnet/templates/daemonsets.yaml
build/charts/hybridnet/templates/deployments.yaml
build/charts/hybridnet/templates/networkinitialization.yaml
build/charts/hybridnet/templates/webhookconfigurations.yaml
build/charts/hybridnet/values.yaml
build/imageList

Upgrade hybridnet to fix bug.

---

build/charts/calico/values.yaml
build/charts/kube-core/Chart.yaml
build/charts/kube-core/templates/kube-proxy.yaml
build/charts/kube-core/templates/metrics-server.yml
build/charts/kube-core/values.yaml
build/imageList
build/kubeadm.yml

upgread 1.22
modify kubeadm.yaml , /build/charts/kube-core , imageList

[WIP]upgread 1.22

---

.github/workflows/auto-build.yml
build/charts/hybridnet/README.md

New release 3

---

.github/workflows/auto-build.yml
test/sealer_calico_test.go
test/sealer_hybirdnet_test.go
test/testhelper/settings/common.go

modify scripe

---

.github/workflows/auto-build.yml
test/sealer_calico_test.go
test/sealer_hybirdnet_test.go
test/testhelper/settings/common.go

autobuild add e2e test

---

build/Kubefile

base image

---

.github/workflows/e2e-test-calico.yml
.github/workflows/e2e-test-hybirdnet.yml

delete excess wget

---

test/testhelper/settings/common.go

modify default image name

---

build/Kubefile
build/kubeadm.yaml.tmpl

add podCIDR variable

---

.github/workflows/auto-build.yml

modify image name

---

test/suites/apply/fixtures/cluster_file_for_test.yaml

modify cluster name

---

build/plugins/disk_init_rollback_shell_plugin.yaml

Should not clean etcd device on worker.

---

.github/workflows/auto-build.yml
.github/workflows/e2e-test-calico.yml
.github/workflows/e2e-test-hybirdnet.yml
test/sealer_calico_test.go
test/sealer_hybirdnet_test.go
test/suites/apply/fixtures/cluster_file_for_test.yaml

Change the action triggering mode

---

test/sealer_calico_test.go

delete e2etest node

---

test/sealer_calico_test.go

use goroutine exec script

---

build/Kubefile
build/plugins/umount_master_etcd_shell_plugin.yaml

PreClean umount etcd

---

build/fetch-hybridnet.sh

update hybridnet chart to 0.3.0

---

build/charts/csi-minio/Chart.yaml
build/charts/csi-minio/templates/csi-minio.yaml
build/charts/csi-minio/templates/external-minio-svc.yaml
build/charts/csi-minio/templates/provisioner.yaml
build/charts/csi-minio/templates/rbac.yaml
build/charts/csi-minio/templates/resizer.yaml
build/charts/csi-minio/templates/secret.yaml
build/charts/csi-minio/templates/storageclass.yaml
build/charts/csi-minio/values.yaml
build/charts/hybridnet/Chart.yaml
build/charts/hybridnet/crds/networking.alibaba.com_ipinstances.yaml
build/charts/hybridnet/crds/networking.alibaba.com_networks.yaml
build/charts/hybridnet/templates/daemonsets.yaml
build/charts/hybridnet/templates/deployments.yaml
build/charts/hybridnet/values.yaml
build/charts/open-local/Chart.yaml
build/charts/open-local/templates/storage-class.yaml
build/charts/open-local/values.yaml
build/fetch-hybridnet.sh
build/imageList
build/kubeadm.yml
build/kubeadm.yml.tmpl
build/plugins/disk_init_rollback_shell_plugin.yaml
build/plugins/install_addons_shell_plugin.yaml
build/plugins/umount_master_etcd_shell_plugin.yaml
build/scripts/install_addons.sh
build/yamls/coredns-cm.yaml

Check 1.22

---

go.mod
vendor/github.com/alibaba/sealer/utils/ssh/utils.go
vendor/github.com/onsi/gomega/.travis.yml
vendor/github.com/onsi/gomega/CHANGELOG.md
vendor/github.com/onsi/gomega/Dockerfile
vendor/github.com/onsi/gomega/Makefile
vendor/github.com/onsi/gomega/docker-compose.yaml
vendor/github.com/onsi/gomega/gomega_dsl.go
vendor/github.com/onsi/gomega/internal/assertion/assertion.go
vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
vendor/github.com/onsi/gomega/internal/oraclematcher/oracle_matcher.go
vendor/github.com/onsi/gomega/internal/testingtsupport/testing_t_support.go
vendor/modules.txt

modify vendor

---

build/plugins/install_addons_shell_plugin.yaml

fix network type bug.

---

build/Kubefile

delete Kubefile redundant parameter

---

.github/workflows/auto-build.yml
build/Kubefile

Support multiple architectures

---

.github/workflows/e2e-test-hybirdnet.yml

change sealer binary

---

build/fetch-hybridnet.sh

update hybridnet chart to 0.3.1

---

build/charts/paralb/Chart.yaml
build/charts/paralb/templates/crds.yaml
build/charts/paralb/templates/daemonsets.yaml
build/charts/paralb/templates/rbac.yaml
build/charts/paralb/templates/services.yaml
build/charts/paralb/templates/webhookconfigurations.yaml
build/charts/paralb/values.yaml
build/imageList

introduce paralb

---

build/charts/kube-core/templates/local-dns-cache.yaml
build/charts/kube-core/values.yaml

introduce local-dns-cache

---

.github/workflows/test.yml
test/ackdtest_test.go

Add delete cluster condition

---

.github/workflows/test.yml

optimization test

---

.github/workflows/test.yml

modify sealer release

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/README.md
build/chart/hybridnet/crds/networking.alibaba.com_networks.yaml
build/chart/hybridnet/templates/daemonsets.yaml
build/chart/hybridnet/templates/deployments.yaml
build/chart/hybridnet/templates/rbac.yaml
build/chart/hybridnet/values.yaml
build/fetch-hybridnet.sh
build/scripts/install_addons.sh

update hybridnet chart to 0.4.0

---

build/imageList

update hybridnet image to v0.6.0 in image list

---

.github/workflows/test.yml
test/testhelper/settings/common.go

Added test image name selection
ex:/test imageName network e2e clean

Added test image name selection

---

build/chart/ack-node-problem-detector/values.yaml
build/imageList

update image tag

---

.github/workflows/test.yml
test/ackdtest_test.go

Optimize automated test

---

test/ackdtest_test.go
test/suites/apply/apply.go
test/testhelper/settings/common.go

Copy the clusterfile to the execution machine

---

test/ackdtest_test.go

delete local Clusterfile

---

.github/workflows/auto-build.yml
.github/workflows/test.yml

Modify the action trigger method

---

.github/workflows/auto-build.yml

add image build redirect

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/README.md
build/chart/hybridnet/crds/multicluster.alibaba.com_remoteendpointslice.yaml
build/chart/hybridnet/templates/configmaps.yaml
build/chart/hybridnet/templates/daemonsets.yaml
build/chart/hybridnet/templates/deployments.yaml
build/chart/hybridnet/templates/rbac.yaml
build/chart/hybridnet/templates/webhookconfigurations.yaml
build/chart/hybridnet/values.yaml
build/fetch-hybridnet.sh
build/imageList
build/scripts/install_addons.sh

update hybridnet chart to 0.5.0 and image to v0.7.0

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/templates/daemonsets.yaml

update hybridnet chart to 0.5.3

---

build/scripts/uninstall-docker.sh

rename clean.sh to uninstall-docker.sh: delete some clean kube logic

---

build/chart/csi-hostpath/Chart.yaml
build/chart/csi-hostpath/templates/csi-plugin.yaml
build/chart/csi-hostpath/templates/driverinfo.yaml
build/chart/csi-hostpath/templates/rbac.yaml
build/chart/csi-hostpath/templates/storageclass.yaml
build/chart/csi-hostpath/values.yaml
build/imageList

add csi-hostpath

---

build/build.sh

add default os for sealer build

---

build/chart/open-local/templates/init-job.yaml

bugfix: wrong podAntiAffinity in yoda-init-job

---

build/build.sh

add velero binary

---

build/chart/open-local/values.yaml

update open-local image to v0.6.0

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/templates/daemonsets.yaml
build/chart/hybridnet/templates/deployments.yaml
build/chart/hybridnet/values.yaml
build/fetch-hybridnet.sh
build/imageList

update hybridnet chart to v0.5.7

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/crds/multicluster.alibaba.com_remotevteps.yaml
build/chart/hybridnet/crds/networking.alibaba.com_nodeinfoes.yaml
build/chart/hybridnet/templates/daemonsets.yaml
build/chart/hybridnet/templates/deployments.yaml
build/chart/hybridnet/templates/services.yaml
build/chart/hybridnet/values.yaml

update hybridnet chart to 0.5.8

---

build/chart/hybridnet/values.yaml

feat(network): enable hybridnet VMIPRetain feature-gate default

---

build/chart/open-local/templates/controller.yaml
build/chart/open-local/templates/storage-class.yaml

add tolerations for yoda

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/templates/daemonsets.yaml
build/chart/hybridnet/templates/deployments.yaml
build/chart/hybridnet/templates/networkinitialization.yaml
build/chart/hybridnet/templates/services.yaml
build/chart/hybridnet/values.yaml

update hybridnet chart to 0.5.9

---

build/chart/open-local/templates/storage-class.yaml

add velero label for volumesnapshotclass

---

build/chart/csi-hostpath/templates/storageclass.yaml
build/chart/open-local/templates/storage-class.yaml

update storage class annotations

---

build/chart/csi-hostpath/templates/storageclass.yaml

csi-hostpath pv support non-root user

---

auto-build-base-rootfs.sh
context/Kubefile
context/docker/rootfs/etc/docker.service
context/download.sh
context/rootfs/etc/10-kubeadm.conf
context/rootfs/etc/docker.service
context/rootfs/etc/kubelet.service
context/rootfs/etc/registry_config.yml
context/rootfs/lib/install_libseccomp.sh
context/version.sh

---
use:
bash auto-build-base-rootfs.sh --tag=v2.0

support auto build base image

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/templates/daemonsets.yaml
build/chart/hybridnet/templates/deployments.yaml
build/chart/hybridnet/templates/networkinitialization.yaml
build/chart/hybridnet/values.yaml

update hybridnet chart to 0.5.12

---

build/chart/paralb/templates/networkinitialization.yaml
build/chart/paralb/values.yaml

---
We update a new version of paralb to support dual-stack. Meaning that, the LoadBalancer services in k8s could have dual-stack vips as external-ips supplied by Paralb.
Fixes #176

[paralb] update. supporting dual stack.

---

build/statics/kube-scheduler-config.yaml
build/v1.20.11-aliyun.1/imageList-standard
build/v1.22.15-aliyun.1/imageList-standard

update koord-scheduler version

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/values.yaml
build/plugins/post_install_shell_plugin.yaml
build/scripts/install_addons.sh
build/v1.20.11-aliyun.1/imageList-standard
build/v1.22.15-aliyun.1/imageList-standard

update hybridnet chart to v0.5.13

---

build/statics/kube-scheduler-config.yaml

update koord-scheduler config

---

build/v1.20.11-aliyun.1/imageList-standard
build/v1.22.15-aliyun.1/imageList-standard

update koord-scheduler image

---

build/chart/open-local/values-acka.yaml

update open-local image

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/crds/networking.alibaba.com_networks.yaml
build/chart/hybridnet/templates/deployments.yaml
build/chart/hybridnet/values.yaml

update hybridnet chart to v0.6.0

---

build/scripts/install_addons.sh
build/v1.20.11-aliyun.1/chart/kube-core/templates/local-dns-cache.yaml
build/v1.22.15-aliyun.1/chart/kube-core/templates/local-dns-cache.yaml

update networking component resources

---

build/chart/open-local/templates/rbac.yaml
build/chart/open-local/values.yaml
build/v1.20.11-aliyun.1/imageList-standard
build/v1.22.15-aliyun.1/imageList-standard

update open-local version to v0.7.0

---

build/chart/csi-hostpath/templates/storageclass.yaml

update csi-hostpath description

---

build/chart/ack-node-problem-detector/templates/node-problem-detector.yaml
build/chart/ack-node-problem-detector/values.yaml
build/chart/open-local/templates/agent.yaml
build/chart/open-local/templates/controller.yaml
build/chart/open-local/values.yaml
build/scripts/install_addons.sh
build/scripts/post_init_master.sh
build/scripts/upgrade-trident-addons.sh
build/v1.20.11-aliyun.1/chart/kube-core/templates/coredns.yaml
build/v1.20.11-aliyun.1/chart/kube-core/templates/metrics-server.yml
build/v1.20.11-aliyun.1/chart/kube-core/values.yaml
build/v1.20.11-aliyun.1/etc/kubeadm.yml.tmpl
build/v1.22.15-aliyun.1/chart/kube-core/templates/coredns.yaml
build/v1.22.15-aliyun.1/chart/kube-core/templates/metrics-server.yml
build/v1.22.15-aliyun.1/chart/kube-core/values.yaml
build/v1.22.15-aliyun.1/etc/kubeadm.yml.tmpl

Support ClusterScale.

---

build/scripts/install_addons.sh
build/scripts/upgrade-trident-addons.sh
build/v1.20.11-aliyun.1/chart/kube-core/values.yaml
build/v1.20.11-aliyun.1/etc/kubeadm.yml.tmpl
build/v1.22.15-aliyun.1/chart/kube-core/values.yaml
build/v1.22.15-aliyun.1/etc/kubeadm.yml.tmpl

fix invalid local-dns ip

---

build/scripts/upgrade-k8s-v2.sh

---
delete kubelet-certificate-authority in upgrade-k8s-v2.sh

fix kubelet cert

---

build/statics/kube-scheduler-config.yaml
build/v1.20.11-aliyun.1/statics/kube-scheduler-config.yaml
build/v1.22.15-aliyun.1/statics/kube-scheduler-config.yaml

disable koord-scheduler profiling

---

build/scripts/upgrade-container-runtime.sh

---
support upgrade container runtime

support upgrade container runtime

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/values.yaml
build/image-anno-v1.20.11-aliyun.1
build/image-anno-v1.22.15-aliyun.1
build/scripts/upgrade-trident-addons.sh
build/v1.20.11-aliyun.1/imageList-standard
build/v1.22.15-aliyun.1/imageList-standard

update hybridnet chart to v0.6.6

---

build/chart/hybridnet/Chart.yaml
build/chart/hybridnet/crds/multicluster.alibaba.com_remoteclusters.yaml
build/chart/hybridnet/crds/multicluster.alibaba.com_remoteendpointslice.yaml
build/chart/hybridnet/crds/networking.alibaba.com_ipinstances.yaml
build/chart/hybridnet/templates/daemonsets.yaml
build/chart/hybridnet/values.yaml
build/image-anno-v1.20.11-aliyun.1
build/image-anno-v1.22.15-aliyun.1
build/scripts/upgrade-trident-addons.sh
build/v1.20.11-aliyun.1/imageList-standard
build/v1.22.15-aliyun.1/imageList-standard

update hybridnet chart to v0.6.7

---

build/chart/hybridnet/values.yaml

fix: hybridnet webhook is not working due to wrong pod match expressions
